// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY-eagohZexYJKPqqSFJQZy5BnckHoZew',
    appId: '1:781766333218:web:b50816c25c7c2e98c30b7b',
    messagingSenderId: '781766333218',
    projectId: 'tiktok-clone-kwh9788',
    authDomain: 'tiktok-clone-kwh9788.firebaseapp.com',
    storageBucket: 'tiktok-clone-kwh9788.appspot.com',
    measurementId: 'G-VFN7J24XW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Az6uy_wWiEYfdevEOakUJjC_VKUZJVw',
    appId: '1:781766333218:android:ef2c6561662fd3e3c30b7b',
    messagingSenderId: '781766333218',
    projectId: 'tiktok-clone-kwh9788',
    storageBucket: 'tiktok-clone-kwh9788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAqq2r2q_OWLsRe5iHBmsQzMokKOGpew',
    appId: '1:781766333218:ios:bb71d092e8f187c7c30b7b',
    messagingSenderId: '781766333218',
    projectId: 'tiktok-clone-kwh9788',
    storageBucket: 'tiktok-clone-kwh9788.appspot.com',
    iosClientId: '781766333218-071tr4fdt1e6d17v9ag9hsrvm86p2jei.apps.googleusercontent.com',
    iosBundleId: 'com.kwh9788.tiktokClone',
  );
}
